# Регистрация нового пользователя
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "someone1@yahoo.com",
  "fullName": "John Doe",
  "password": "anonimus1"
}

###

# Login user by email and password
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "someone@yahoo.com",
  "password": "anonimus1"
}

###

# Get new JWT pair
POST http://localhost:3000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk2NGJlMzM0ZGJkMWMwMTIwYmU1OWMiLCJlbWFpbCI6InNvbWVvbmVAeWFob28uY29tIiwiZnVsbE5hbWUiOiJKb2huIERvZSIsInRva2VuSWQiOiI3MDBmNTE4NC1iMTdjLTQwNmQtOWI3MC04ODgyNGFlZDUxM2MiLCJpYXQiOjE3Mzc5MDY1MjQsImV4cCI6MTc0MDQ5ODUyNH0.yY_djRP4SEnfkUSPxc872ZkE1gjnbMo-bbjDW4y5EJM

###

# Create new post
POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk2NGJlMzM0ZGJkMWMwMTIwYmU1OWMiLCJlbWFpbCI6InNvbWVvbmVAeWFob28uY29tIiwiZnVsbE5hbWUiOiJKb2huIERvZSIsImlhdCI6MTczNzkwNjM0NywiZXhwIjoxNzM3OTA2NjQ3fQ.8M5_5sUjKXJb4o4mlxObc0JflG9U6W8J9UD5JvSL7U4

{
  "type": "QUOTA",
  "quotaAuthor": "Jack London",
  "quotaText": "Real purpose of the person — to live, instead of to exist",
  "tags": ["one", "two"]
}

###
