# Регистрация нового пользователя
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "321@yahoo.com",
  "fullName": "Any Cravetz",
  "password": "anonimus1"
}

###


# Получить детальную информацию о пользователе по ID
GET http://localhost:3000/api/users/67a236123dccda2d52fd6199 HTTP/1.1

###


# Авторизация с помощью почты и пароля
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "321@yahoo.com",
  "password": "anonimus1"
}

###


# Получение новой пары JWT ключей
POST http://localhost:3000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2EyMmViZmNlNTZhNTI3ZjYxZTkzOGEiLCJlbWFpbCI6InRlc3RAeWFob28uY29tIiwiZnVsbE5hbWUiOiJKb2huIERvZSIsInRva2VuSWQiOiI0NjU1MDdmMC1jNTQ5LTQ2ZjEtYTI2YS1jZjMwMDBmNGM1ODAiLCJpYXQiOjE3Mzg2ODIxMDUsImV4cCI6MTc0MTI3NDEwNX0.ICkxMqr7zl6vkpzA61alpVZIHBm7h1w-l001frG74Lg

###


# Создание нового поста
POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2N2EyMmViZmNlNTZhNTI3ZjYxZTkzOGEiLCJlbWFpbCI6InRlc3RAeWFob28uY29tIiwiZnVsbE5hbWUiOiJKb2huIERvZSIsImlhdCI6MTczODY4MjEzOCwiZXhwIjoxNzM4NjgyNDM4fQ.LchDi4Kwvfh_2YyN_FNKQ3epK4MVoqp__MNYMSsNRNE

{
  "type": "QUOTA",
  "quotaAuthor": "Jack London",
  "quotaText": "Real purpose of the person — to live, instead of to exist",
  "tags": ["one", "two"]
}

###
