# Create a new user
POST http://localhost:3000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "nouser@myspace.com",
  "fullName": "John Doe",
  "password": "anonimus1"
}

###

# Get user by ID
GET http://localhost:3000/api/users/67713cfffe94dce9f9a16b81 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "nouser@myspace.com",
  "password": "anonimus1"
}

###
