# Create a comment
POST http://localhost:3000/api/comments/ HTTP/1.1
Content-Type: application/json

{
  "postId": "2fd35496-c6fd-4a21-bbf5-e0ada55dc810",
  "text": "New one is not enoth)",
  "authorId": "676428b948541ea480d114fb"
}

###

# Get comment by ID
GET http://localhost:3000/api/comments/fa298d24-0e96-4dac-ad08-11ac89302060 HTTP/1.1

###

# Update comment by ID
PATCH http://localhost:3000/api/comments/03fc9404-8aba-47ab-ba59-48aaecb83a45 HTTP/1.1
Content-Type: application/json

{
  "id": "03fc9404-8aba-47ab-ba59-48aaecb83a45",
  "postId": "2fd35496-c6fd-4a21-bbf5-e0ada55dc810",
  "text": "Updated text"
}
###

# Delete comment by ID
DELETE http://localhost:3000/api/comments/9b83aa3a-4fb5-49be-b4fc-b57418e8e139 HTTP/1.1

###

# Get all comments by post ID
# You can specify page, limit ad sort direction as well
GET http://localhost:3000/api/comments?postId=4ee1d10b-81fd-4370-b0a4-849c92476c53&limit=3&page=1 HTTP/1.1

###

# Get all comments in database
GET http://localhost:3000/api/comments/ HTTP/1.1

###
