# Create a comment
POST http://localhost:3000/api/comments/ HTTP/1.1
Content-Type: application/json

{
  "postId": "8a1acb92-d765-4c5d-a1ef-aaef57c7cc5d",
  "text": "Second One",
  "authorId": "676428b948541ea480d114fb"
}

###

# Get comment by ID
GET http://localhost:3000/api/comments/fa298d24-0e96-4dac-ad08-11ac89302060 HTTP/1.1

###

# Update comment by ID
PATCH http://localhost:3000/api/comments/adebb020-69b5-4c20-8e91-d9d28667134b HTTP/1.1
Content-Type: application/json

{
  "text": "Updated text"
}
###

# Delete comment by ID
DELETE http://localhost:3000/api/comments/adebb020-69b5-4c20-8e91-d9d28667134b HTTP/1.1

###

# Get all comments by post ID
# You can specify page, limit ad sort direction as well
GET http://localhost:3000/api/comments?postId=8a1acb92-d765-4c5d-a1ef-aaef57c7cc5d&limit=3&page=1 HTTP/1.1

###

# Get all comments in database
GET http://localhost:3000/api/comments/ HTTP/1.1

###
