# Create new post
POST http://localhost:3020/api/posts/ HTTP/1.1
Content-Type: application/json

{
  "userId": "676428b948541ea480d114fb",
  "type": "QUOTA",
  "quotaAuthor": "Jack London",
  "quotaText": "Real purpose of the person — to live, instead of to exist",
  "tags": ["life", "love"]
}

###

# Get all posts
# You will get latest 25 (or less) published post in page by default
GET http://localhost:3020/api/posts HTTP/1.1

###

# Get posts with some limits. You can specify one or combine some limits as you wish
# Examples below

# You can specify page, limit ad sort direction as well:
# limit = [number] page = [number] sortDirection = asc | desc
GET http://localhost:3020/api/posts?limit=3&page=1&sortDirection=asc HTTP/1.1

###

# To sort by post type:
# type = text | video | qouta | photo | link (in any register)
GET http://localhost:3020/api/posts?type=video HTTP/1.1

###

# Sorting by fields:
# sortType = createdAt | updatedAt | comments | likes
GET http://localhost:3020/api/posts?sortType=comments HTTP/1.1

###

# Get post with special status:
# status = all | draft | published (in any register)
GET http://localhost:3020/api/posts?status=published HTTP/1.1

###

# Get post by tag
GET http://localhost:3020/api/posts?tag=life HTTP/1.1

###

# Get post by ID
GET http://localhost:3020/api/posts/02c504b9-c8ec-45cb-a887-21885c1b9ab2 HTTP/1.1

###

# Update post by ID
PATCH http://localhost:3020/api/posts/b099f6e6-bcf3-444f-8498-a3d161c92068 HTTP/1.1
Content-Type: application/json

{
  "type": "QUOTA",
  "quotaText": "Not good idea sdfjjkfdjk sdfkljklsdfj",
  "published": "false"
}

###

# Delete post by ID
DELETE http://localhost:3020/api/posts/0ba290e4-5f5e-4114-bec5-5bfff19d943a HTTP/1.1

###
