# Create new post (qouta)
POST http://localhost:3020/api/posts/ HTTP/1.1
Content-Type: application/json

{
  "userId": "6798b06010b4fa31970d79fd",
  "type": "QUOTA",
  "quotaAuthor": "Albert Einstein",
  "quotaText": "Only two things are infinite — the universe and human stupidity, and I'm not sure about the former."
}
###

# Create new post (text)
POST http://localhost:3020/api/posts/ HTTP/1.1
Content-Type: application/json

{
  "userId": "6798b06010b4fa31970d79fd",
  "type": "TEXT",
  "textTitle": "Were the Maya right: 'Are we going to die?'",
  "textDescription": "The article examines the beliefs of the Maya people that have survived to the present day.",
  "textContent": "Absolutely all great civilizations leave prophecies and prescriptions to their descendants. Maya, as one of the most famous ancient ones, was no exception. Surprisingly, the Maya predicted many dates on which many important events for humanity were to take place. If great human minds have correctly deciphered the prophecies of the Maya, then people should meet the New Era on their way. But there is a fear that a New Era will come along with many natural disasters that will affect the whole world."
}

###

# Create new post (link)
POST http://localhost:3020/api/posts/ HTTP/1.1
Content-Type: application/json

{
  "userId": "6798b06010b4fa31970d79fd",
  "type": "LINK",
  "linkUrl": "https://ya.ru/",
  "linkDescription": "Advanced multilingual search engine"
}

###

# Create new post (video)
POST http://localhost:3020/api/posts/ HTTP/1.1
Content-Type: application/json

{
  "userId": "6798b06010b4fa31970d79fd",
  "type": "video",
  "videoTitle": "Funny cats sliping and playing",
  "videoUrl": "https://www.youtube.com/watch?v=F6va6tg62qg"
}

###


# Get all posts
# You will get latest 25 (or less) published post in page by default
GET http://localhost:3020/api/posts HTTP/1.1

###

# Get posts with some limits. You can specify one or combine some limits as you wish
# Examples below

# You can specify page, limit ad sort direction as well:
# limit = [number] page = [number] sortDirection = asc | desc
GET http://localhost:3020/api/posts?limit=3&page=1&sortDirection=asc HTTP/1.1

###

# To sort by post type:
# type = text | video | qouta | photo | link (in any register)
GET http://localhost:3020/api/posts?type=video HTTP/1.1

###

# Sorting by fields:
# sortType = createdAt | updatedAt | comments | likes
GET http://localhost:3020/api/posts?sortType=comments HTTP/1.1

###

# Get post with special status:
# status = all | draft | published (in any register)
GET http://localhost:3020/api/posts?status=published HTTP/1.1

###

# Get post by tag
GET http://localhost:3020/api/posts?tag=life HTTP/1.1

###

# Get post by userId
GET http://localhost:3020/api/posts?author=6798b06010b4fa31970d79fd HTTP/1.1

###

# Get post by ID
GET http://localhost:3020/api/posts/02c504b9-c8ec-45cb-a887-21885c1b9ab2 HTTP/1.1

###

# Update post by ID
PATCH http://localhost:3020/api/posts/b099f6e6-bcf3-444f-8498-a3d161c92068 HTTP/1.1
Content-Type: application/json

{
  "type": "QUOTA",
  "quotaText": "Not good idea sdfjjkfdjk sdfkljklsdfj",
  "published": "false"
}

###

# Delete post by ID
DELETE http://localhost:3020/api/posts/9773182d-89de-4216-a2bb-3f1f04ea895e HTTP/1.1

###

# Repost post by ID
POST http://localhost:3020/api/posts/c6040bde-40e9-47d5-86fb-70904e05de01/repost HTTP/1.1
Content-Type: application/json

{
  "userId": "67a2880044b90afb6ec75bad"
}

###
